
apiVersion: srlinux.henderiw.be/v1alpha1
kind: K8sSrlNokiaNetworkInstanceNetworkInstanceProtocolsBgpevpn
metadata:
  name: infrastructure-40-protocolbgpevpn-leaf1
  labels:
    target: leaf1
spec:
  network-instance-name: infrastructure-macvrf-itfce-40
  bgp-evpn:
    bgp-instance:
    - id: "1"
      admin-state: enable
      ecmp: 8
      evi: 40
      vxlan-interface: vxlan0.40
