
apiVersion: srlinux.henderiw.be/v1alpha1
kind: K8sSrlNokiaNetworkInstanceNetworkInstanceProtocolsBgpVpn
metadata:
  name: protocolbgpvpn-infrastructuremacvrfitfce40-leaf1
  labels:
    target: leaf1
spec:
  network-instance-name: infrastructuremacvrfitfce40
  bgp-vpn:
    bgp-instance:
    - id: 1
      route-target:
        export-rt: target:65002:40
        import-rt: target:65002:40
