
apiVersion: srlinux.henderiw.be/v1alpha1
kind: K8sSrlNokiaNetworkInstanceNetworkInstance
metadata:
  name: infra-default-network-instance-leaf2
  labels:
    target: leaf2
spec:
  network-instance:
  - name: default
    type: default
    admin-state: enable
    description: paco-default
    interface:
    - name: ethernet-1/49.0
    - name: system0.0
