apiVersion: srlinux.henderiw.be/v1alpha1
kind: K8sSrlNokiaInterfacesInterfaceSubinterface
metadata:
  name: subinterface-paco-infra-leaf1
  labels:
    target: leaf2
spec:
  interface-name: ethernet-1/49
  subinterface:
  - index: 0
    type: routed
    admin-state: enable
    description: "paco-e1-49.0"
    ipv4:
      address: 
      - ip-prefix: 100.64.0.1/31