
apiVersion: srlinux.henderiw.be/v1alpha1
kind: K8sSrlNokiaTunnelInterfacesTunnelInterface
metadata:
  name: tunnel-interface-vxlan0-paco
  labels:
    target: leaf-grp1
spec:
  tunnel-interface:
  - name: vxlan0
