
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- vxlaninterface-vxlan0-leaf2.yaml
- subinterface-lag1-leaf2.yaml
- subinterface-lag2-leaf2.yaml
- network-instance-0-leaf2.yaml
- network-instance-protocol-bgpvpn0-leaf2.yaml
- network-instance-protocol-bgpevpn0-leaf2.yaml
- network-instance-protocol-linux0-leaf2.yaml
- vxlaninterface-vxlan0-leaf1.yaml
- subinterface-lag1-leaf1.yaml
- subinterface-lag2-leaf1.yaml
- network-instance-0-leaf1.yaml
- network-instance-protocol-bgpvpn0-leaf1.yaml
- network-instance-protocol-bgpevpn0-leaf1.yaml
- network-instance-protocol-linux0-leaf1.yaml
