
apiVersion: srlinux.henderiw.be/v1alpha1
kind: K8sSrlNokiaNetworkInstanceNetworkInstanceProtocolsBgpVpn
metadata:
  name: provisioningMacVrfitfce0
  labels:
    target: leaf2
spec:
  network-instance-name: provisioningMacVrfitfce0
  bgp-vpn:
    bgp-instance:
      id: 1
      route-target:
        export-rt: target:65002:0
        import-rt: target:65002:0
