
apiVersion: srlinux.henderiw.be/v1alpha1
kind: K8sSrlNokiaNetworkInstanceNetworkInstance
metadata:
  name: provisioning-1-network-instance-leaf1
  labels:
    target: leaf1
spec:
  network-instance:
  - name: provisioning-macvrf-itfce-0
    type: mac-vrf
    admin-state: enable
    description: paco-provisioning-macvrf-itfce-0
    interface:
    - name: lag1.0
    - name: lag2.0
    vxlan-interface:
    - name: vxlan0.0
    bridge-table:
      mac-duplication:
        admin-state: enable
        action: blackhole
