
apiVersion: srlinux.henderiw.be/v1alpha1
kind: K8sSrlNokiaNetworkInstanceNetworkInstanceProtocolsBgpVpn
metadata:
  name: multus-mgmt-102-protocolbgpvpn-leaf1
  labels:
    target: leaf1
spec:
  network-instance-name: multus-macvrf-sriov-102
  bgp-vpn:
    bgp-instance:
    - id: 1
      route-target:
        export-rt: target:65002:102
        import-rt: target:65002:102
